const angular = require("angular")
const uirouter = require("angular-ui-router")
const nganimate = require("angular-animate")

const router = require("./router")
const C = require("./services/Const")
const Math2 = require("./services/Math2")
const Utils = require("./services/Utils")
const Events = require("./services/Events")
const Sharer = require("./services/Sharer")
const Delaunay = require("./services/Delaunay")
const Textures = require("./services/Textures")
const DataLoader = require("./services/DataLoader")
const Performance = require("./services/Performance")
const ThreeManager = require("./services/ThreeManager")
const SoundManager = require("./services/SoundManager")
const AssetsLoader = require("./services/AssetsLoader")
const AppController = require("./controllers/AppController")
const CanvasController = require("./controllers/CanvasController")
const SectionsController = require("./controllers/SectionsController")
const ProjectsController = require("./controllers/ProjectsController")
const InfosController = require("./controllers/InfosController")
const DisplayObject = require("./factories/core/DisplayObject")
const ContainerObject = require("./factories/core/ContainerObject")
const SectionObject = require("./factories/core/SectionObject")
const ThreeObject = require("./factories/core/ThreeObject")
const Menu = require("./factories/sections/Menu")
const Index = require("./factories/sections/Index")
const Work = require("./factories/sections/Work")
const About = require("./factories/sections/About")
const Contacts = require("./factories/sections/Contacts")
const Wall = require("./factories/sections/Wall")
const Leaf = require("./factories/sections/Leaf")
const Infos = require("./factories/sections/Infos")
const CLeaf = require("./factories/sections/CLeaf")
const Text = require("./factories/sprites/Text")
const Arrow = require("./factories/sprites/Arrow")
const Poster = require("./factories/sprites/Poster")
const Visual = require("./factories/sprites/Visual")
const Fragment = require("./factories/sprites/Fragment")
const Scroller = require("./factories/sprites/Scroller")
const Maincta = require("./factories/sprites/Maincta")
const Leafcta = require("./factories/sprites/Leafcta")
const Caption = require("./factories/sprites/Caption")
const Numnav = require("./factories/sprites/Numnav")
const Bread = require("./factories/sprites/Bread")
const Copy = require("./factories/sprites/Copy")
const Back = require("./factories/sprites/Back")
const Hamb = require("./factories/sprites/Hamb")
const Mouse = require("./factories/sprites/Mouse")
const Specs = require("./factories/sprites/Specs")
const Holdrag = require("./factories/sprites/Holdrag")
const Menugrid = require("./factories/sprites/Menugrid")
const Identity = require("./factories/sprites/Identity")
const Benchmark = require("./factories/sprites/Benchmark")
const Aboutintro = require("./factories/sprites/Aboutintro")
const Clients = require("./factories/sprites/Clients")
const InfoScene = require("./factories/three/InfoScene")
const MenuScene = require("./factories/three/MenuScene")
const ThreeFactory = require("./factories/three/ThreeFactory")
const TerrainGeneration = require("./factories/three/TerrainGeneration")
const PostProcessing = require("./factories/PostProcessing")
const Preloader = require("./factories/Preloader")
const UIfactory = require("./factories/UIfactory")
const SiteUI = require("./factories/SiteUI")
const AppStage= require("./directives/AppStage")
const Debugger = require("./directives/Debugger")

angular.module("UprsgApp", ["ui.router", "ngAnimate"])
    .service("Math2", Math2)
    .service("Const", C)
    .service("Utils", Utils)
    .service("Events", Events)
    .service("Sharer", Sharer)
    .service("Delaunay", Delaunay)
    .service("Textures", Textures)
    .service("DataLoader", DataLoader)
    .service("Performance", Performance)
    .service("ThreeManager", ThreeManager)
    .service("SoundManager", SoundManager)
    .service("AssetsLoader", AssetsLoader)
    .controller("AppController", AppController)
    .controller("CanvasController", CanvasController)
    .controller("SectionsController", SectionsController)
    .controller("ProjectsController", ProjectsController)
    .controller("InfosController", InfosController)
    .factory("DisplayObject", DisplayObject)
    .factory("ContainerObject", ContainerObject)
    .factory("SectionObject", SectionObject)
    .factory("ThreeObject", ThreeObject)
    .factory("PostProcessing", PostProcessing)
    .factory("TerrainGeneration", TerrainGeneration)
    .factory("Preloader", Preloader)
    .factory("Benchmark", Benchmark)
    .factory("InfoScene", InfoScene)
    .factory("MenuScene", MenuScene)
    .factory("ThreeFactory", ThreeFactory)
    .factory("UIfactory", UIfactory)
    .factory("SiteUI", SiteUI)
    .factory("Menugrid", Menugrid)
    .factory("Menu", Menu)
    .factory("Index", Index)
    .factory("Work", Work)
    .factory("About", About)
    .factory("Contacts", Contacts)
    .factory("Wall", Wall)
    .factory("Leaf", Leaf)
    .factory("Infos", Infos)
    .factory("CLeaf", CLeaf)
    .factory("Poster", Poster)
    .factory("Visual", Visual)
    .factory("Fragment", Fragment)
    .factory("Scroller", Scroller)
    .factory("Maincta", Maincta)
    .factory("Leafcta", Leafcta)
    .factory("Identity", Identity)
    .factory("Aboutintro", Aboutintro)
    .factory("Clients", Clients)
    .factory("Caption", Caption)
    .factory("Holdrag", Holdrag)
    .factory("Numnav", Numnav)
    .factory("Arrow", Arrow)
    .factory("Bread", Bread)
    .factory("Text", Text)
    .factory("Copy", Copy)
    .factory("Back", Back)
    .factory("Hamb", Hamb)
    .factory("Mouse", Mouse)
    .factory("Specs", Specs)
    .directive("appStage", AppStage)
    .directive("debugger", Debugger)
    .config(router);

angular.element(document).ready(function () {
    angular.bootstrap(document, ["UprsgApp"])
})